services:
  app:
    build: .
    depends_on:
      - db
    volumes:
      - ./:/app
      - /node_modules
    ports:
      - "3000:3000"
  db:
    image: mongo  
    restart: always
    ports:
      - 27017:27017
    volumes:
      - mongodb_data:/data/db
volumes:
  mongodb_data:
