import React from "react"
import "./globals.css"
import type { Metadata } from "next"
import ReduxProvider from "@/providers/ReduxProvider"
import {Jost} from "next/font/google"

export const metadata: Metadata = {
	title: "Product Feedback",
	description: "Generated by create next app",
}

const jost = Jost({
	weight: "400",
	subsets: ["latin"],
	display: "swap"
})

type Props = {
	children: React.ReactNode
	mainFeedbacks: React.ReactNode
	optionsMenu: React.ReactNode
}

export default function RootLayout({
	children,
	mainFeedbacks,
	optionsMenu,
}: Props) {
	return (
		<html lang="en">
			<ReduxProvider>
				<body className={"flex h-screen p-40 justify-center items-center bg-ghost_white " + jost.className}>
					{children}
					{optionsMenu}
					{mainFeedbacks}
				</body>
			</ReduxProvider>
		</html>
	)
}
