import React from "react"
import "./globals.css"
import type { Metadata } from "next"

export const metadata: Metadata = {
	title: "Product Feedback",
	description: "Generated by create next app",
}

type Props = {
	children: React.ReactNode
	mainFeedbacks: React.ReactNode
	optionsMenu: React.ReactNode
}

export default function RootLayout({
	children,
	mainFeedbacks,
	optionsMenu,
}: Props) {
	return (
		<html lang="en">
			<body>
				{children}
				{mainFeedbacks}
				{optionsMenu}
			</body>
		</html>
	)
}
