import React from "react"
import "./globals.css"
import type { Metadata } from "next"
import ReduxProvider from "./providers/ReduxProvider"

export const metadata: Metadata = {
	title: "Product Feedback",
	description: "Generated by create next app",
}

type Props = {
	children: React.ReactNode
	mainFeedbacks: React.ReactNode
	optionsMenu: React.ReactNode
}

export default function RootLayout({
	children,
	mainFeedbacks,
	optionsMenu,
}: Props) {
	return (
		<html lang="en">
			<ReduxProvider>
				<body className="flex h-screen p-40 justify-center items-center bg-ghost_white">
					{children}
					{optionsMenu}
					{mainFeedbacks}
				</body>
			</ReduxProvider>
		</html>
	)
}
