import React from "react"
import "../globals.css"
import type { Metadata } from "next"
import { Jost } from "next/font/google"

export const metadata: Metadata = {
	title: "Product Feedback",
	description: "Generated by create next app",
}

const jost = Jost({
	weight: "400",
	subsets: ["latin"],
	display: "swap",
})

type Props = {
	children: React.ReactNode
	mainFeedbacks: React.ReactNode
	optionsMenu: React.ReactNode
}

export default function Layout({
	mainFeedbacks,
	optionsMenu,
}: Props) {
	return (
		<section
			className={
				"flex justify-center bg-ghost_white p-40 relative" +
				jost.className
			}
		>
			{optionsMenu}
			{mainFeedbacks}
		</section>
	)
}
