import React from "react"
import "../globals.css"
import type { Metadata } from "next"
import { Jost } from "next/font/google"
import { ReactNode } from "react"

export const metadata: Metadata = {
	title: "Product Feedback",
	description: "Generated by create next app",
}

const jost = Jost({
	weight: "400",
	subsets: ["latin"],
	display: "swap",
})

type Props = {
	mainFeedbacks: ReactNode
	optionsMenu: ReactNode
}

export default function Layout({ mainFeedbacks, optionsMenu }: Props) {
	return (
		<section
			className={`relative pt-24 flex justify-center ${jost.className}`}
		>
			{optionsMenu}
			{mainFeedbacks}
		</section>
	)
}
